name: "eggnog_sum"
description: Summarizes EggNOG annotation results
keywords:
  - eggnog
  - summary
  - functional annotation
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - eggnog:
      type: file
      description: EggNOG annotation file
      pattern: "*.emapper.tsv.gz"
  - fcs:
      type: file
      description: Feature counts file
      pattern: "*.counts.tsv.gz"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - eggnog_summary:
      type: file
      description: Summarized EggNOG annotation results
      pattern: "*.eggnog_summary.tsv.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@danilodileo"
