name: eggnog
description: Runs eggNOG-mapper on called ORFs and summarizes the results
keywords:
  - eggnog
  - functional annotation
  - orthology
  - protein sequences
components:
  - eggnog/download
  - eggnog/mapper
  - eggnog/sum
input:
  - faa:
      type: file
      description: Protein sequences in FASTA format
      pattern: "*.{faa,fasta}"
  - collect_fcs:
      type: file
      description: Feature count files
      pattern: "*.counts.tsv.gz"
output:
  - hits:
      type: file
      description: eggNOG-mapper hits file
      pattern: "*.emapper.hits.gz"
  - emappertsv:
      type: file
      description: eggNOG-mapper TSV output file
      pattern: "*.emapper.tsv.gz"
  - sumtable:
      type: file
      description: Summarized eggNOG-mapper results
      pattern: "*.eggnog_summary.tsv.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@danilodileo"
