name: "kofamscan_sum"
description: Summarizes KofamScan results and combines with feature counts
keywords:
  - kofamscan
  - summary
  - functional annotation
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - kofmascan:
      type: file
      description: KofamScan output file
      pattern: "kofamscan_output.tsv.gz"
  - fcs:
      type: file
      description: Feature counts files
      pattern: "*.counts.tsv.gz"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - kofamscan_summary:
      type: file
      description: Summarized KofamScan results
      pattern: "*.kofamscan_summary.tsv.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@danilodileo"
