---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "seqtk_hmmhitfaas"
description: Uses seqtk subseq to output one amino acid fasta file for every profile with hits in a tsv file of ranked HMMER hits
keywords:
  - hmmer
  - seqtk
  - fasta
tools:
  - seqtk:
      description: Seqtk is a fast and lightweight tool for processing sequences in
        the FASTA or FASTQ format. The seqtk seq command enables common transformation
        operations on FASTA or FASTQ files.
      homepage: https://github.com/lh3/seqtk
      documentation: https://docs.csc.fi/apps/seqtk/
      tool_dev_url: https://github.com/lh3/seqtk
      licence: ["MIT"]
      identifier: biotools:seqtk
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
  
    - hmmrank:
        type: file
        description: TSV file containing best ranked HMMER hits
        pattern: "*.tsv.gz"
    - faa:
        type: file
        description: Amino acid fasta file
        pattern: "*.faa.gz"
          

output:
  - hitfaas:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - "hits/*.faa.gz":
        type: file
        description: Subsets of the input fasta file corresponding to hits in the hmmrank file
          
  - versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@erikrikarddaniel"
maintainers:
  - "@erikrikarddaniel"
