name: "format_prodigal_gff"
description: Formats Prodigal GFF output to include contig names in gene IDs
keywords:
  - prodigal
  - gff
  - format
  - gene prediction
input:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - gff:
      type: file
      description: Prodigal GFF output file
      pattern: "*.gff{.gz,}"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - format_gff:
      type: file
      description: Formatted Prodigal GFF file
      pattern: "*_format.gff.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@danilodileo"