name: pipeline_initialisation
description: Initializes the nf-core/metatdenovo pipeline
keywords:
  - initialization
  - parameter validation
  - input processing
components:
  - UTILS_NFSCHEMA_PLUGIN
  - UTILS_NFCORE_PIPELINE
  - UTILS_NEXTFLOW_PIPELINE
input:
  - version:
      type: boolean
      description: Display version and exit
  - validate_params:
      type: boolean
      description: Validate parameters against the schema at runtime
  - monochrome_logs:
      type: boolean
      description: Disable colored log outputs
  - nextflow_cli_args:
      type: array
      description: List of positional Nextflow CLI arguments
  - outdir:
      type: string
      description: The output directory for results
  - input:
      type: string
      description: Path to input samplesheet
  - diamond_dbs:
      type: string
      description: Path to CSV file with Diamond taxonomy databases
output:
  - samplesheet:
      type: channel
      description: Channel containing processed input samples
  - diamond_paths:
      type: channel
      description: Channel containing Diamond database paths
  - versions:
      type: channel
      description: Channel containing software versions
authors:
  - "@danilodileo"

---

name: PIPELINE_COMPLETION
description: Handles pipeline completion tasks for nf-core/metatdenovo
keywords:
  - completion
  - email
  - summary
components:
  - completionEmail
  - completionSummary
  - imNotification
input:
  - email:
      type: string
      description: Email address for completion notification
  - email_on_fail:
      type: string
      description: Email address for failure notification
  - plaintext_email:
      type: boolean
      description: Send plain-text email instead of HTML
  - outdir:
      type: path
      description: Path to output directory
  - monochrome_logs:
      type: boolean
      description: Disable ANSI color codes in log output
  - hook_url:
      type: string
      description: Hook URL for notifications
  - multiqc_report:
      type: string
      description: Path to MultiQC report
output:
  - none
authors:
  - "@danilodileo"